### ISSUE TITLE
mamba-bash-completion request

### ISSUE THREAD

**Issue by sixvable** [tartansandal/conda-bash-completion#10]

**Comment by tartansandal** [comment]
@sixvable Not sure what this request is about. Perhaps you opened this issue by mistake?

**Comment by sixvable** [comment]
@tartansandal  Sorry for the incomplete description about this feature request. I must forgot to submit.

Thanks for the great bash completion for conda. This is exactly what I am looking for. 

I wonder could you also implement the bash completion for [mamba](https://github.com/mamba-org/mamba),  a reimplementation of the conda package manager in C++?

**Comment by tartansandal** [comment]
@sixvable This is definitely something we could. I'll take a closer look a bit later in the week. :smile:

**Comment by tartansandal** [comment]
@sixvable I've made a start on this [here](https://github.com/tartansandal/mamba-bash-completion). It basically works, but I have to sort out one failing test to submit it to conda-forge.

If you want to try it out, just source the `mamba` script in your bash shell. :smiley:

**Comment by tartansandal** [comment]
Hi @sixvable. 

The new [`mamba-bash-completion`](https://github.com/tartansandal/mamba-bash-completion) project has been finalized and the corresponding package is now available on conda-forge. :rocket: 

Hope this works well for you and please let me know if you have any issues under that project.

Thanks for introducing me to mamba and suggesting this project. :smile:
