### ISSUE TITLE
Feature request: Autocomplete on env names?

### ISSUE THREAD

**Issue by tilusnet** [tartansandal/conda-bash-completion#11]
Hi.

Great initiative!
Would you be able to extend support to existing environment names? E.g.:
`conda activate <TAB>`

**Comment by tartansandal** [comment]
Hi @tilusnet 

> Would you be able to extend support to existing environment names? E.g.:
> conda activate <TAB>

That should actually already work. :smile:  Note the positional arg after `activate` is either an "env name" or a "path prefix" so when you hit `<tab>` you may get local sub-directories as completion options as well as your environment names.

Hope that is working for you, but if you have any problems, please let me know and I'll see if I can help.

**Comment by tilusnet** [comment]
Haha I based my assumption on your Readme which does not explicitly mention env name completion.
But you're right, it does work. Awesome!

**Comment by tartansandal** [comment]
Hi @tilusnet! Just a heads up that the new `conda-bash-completion` v1.7 does completion for `conda activate` more like you would expect: completing for named environments by default, and only completing for paths if the stem looks like a path. :smile
