### ISSUE TITLE
doesn't work with m1 mac

### ISSUE THREAD

**Issue by bayeslearner** [tartansandal/conda-bash-completion#14]
**setup.** 

- installed homebrew, 
- bash-completion (not @2)
- then copied conda into /opt/homebrew/etc/bash_completion.d/

**errors**
- syntax error declare -A.  --> changed to declare -a
- after that,  error upon invocation.

**Comment by tartansandal** [comment]
Hi @bayeslearner. 

For completion to work you need both a modern `bash` (version > 4) and `bash-completion` (version > 2) installed. What versions are you using?

To use Installation Method 2, you need to install the `conda`  under `~/.local/share/bash-completion/completions/` or whatever is appropriate for MacOS. I would take a guess that `/opt/homebrew/share/bash-completion/completions/` might work as well, but I don't have a mac to test that on at the moment.

Generally Installation Method 1 is best for MacOS.

**Comment by tartansandal** [comment]
Hi @bayeslearner, 

I note that my previous response may have not been that clear. Sorry about that.

The issue appears to the version of `bash` that you are using. MacOS comes with a very old version of bash (3.2 which dates from 2007) which is fine for running some POSIX bash scripts, but not really suitable for modern interactive use. This is why you get a syntax error with `declare -A`. The upstream [`bash-completion`](https://github.com/scop/bash-completion) library which we depend on requires a bash version >= 4.2, so you will need to upgrade your bash if you want to use any of the advanced completion features. Upgrading bash is possible, either via homebrew or conda, but you probably want to google how to change the location of your shell in MacOS. 

Hope this helps, and feel free to reach out if you are still having issues.

**Comment by tartansandal** [comment]
Hi @bayeslearner. I've not heard from you in a while so I'm closing this issue.

I've made a note in the README about bash versions for MacOS users, hopefully this will help with any future confusion. 

Thanks for reaching out for support :)

**Comment by utkarshgupta137** [comment]
Distributions for M1 macs (osx-arm64 or noarch) are not available.
