### ISSUE TITLE
Feature Request: Conda Activate <tab>

### ISSUE THREAD

**Issue by AMR-** [tartansandal/conda-bash-completion#15]
Hi, I love this project.  Thank you so much.   I have one feature request:

conda activate <tab>

I have a large number of conda environments and this would be my primary tab-completion desire

**Comment by tartansandal** [comment]
Hi @AMR- ! Thanks for the love. Much appreciated. :heart:

This is the 3rd time someone has both been confused by this _and_ raised an issue, so I've modified the completion logic to prioritize completing for "named"  environments over "paths" to environments.  I think very few people use the latter.

I've just issued a new release (1.7) with this fix. You can manually install it from git right now, or wait 48 hours or so for the various bots to do their thing and get an update via `conda`.

Let me know if this fixes the issue for you, or more importantly, if it doesn't :wink:

**Comment by AMR-** [comment]
I updated via conda and it works great.  Thank you so much. :)
