### ISSUE TITLE
No completion on ubuntu 20.04 with conda 22.9.0

### ISSUE THREAD

**Issue by kampelmuehler** [tartansandal/conda-bash-completion#16]
What might be going wrong?

Manually running `source $CONDA_ROOT/etc/profile.d/bash_completion.sh` doesn't help and the paths within `$CONDA_ROOT/etc/profile.d/bash_completion.sh` look sound.

Any help appreciated :)

**Comment by tartansandal** [comment]
Hi @kampelmuehler :wave: 

Do you have conda set up to automatically activate the `base` environment or have you disabled this and used the workaround described in the README.md?

To debug this, you could try running
```
bash -vx  CONDA_ROOT/etc/profile.d/bash_completion.sh
```
to see what is actually being executed. 

A bit busy ATM so I might not be able to get back to this until the weekend.  Happy hunting :smile:

**Comment by kampelmuehler** [comment]
Thanks for getting back on such short notice. For reasons unknown to me it started working on it's own :)
