### ISSUE TITLE
Package for osx-arm64?

### ISSUE THREAD

**Issue by jucor** [tartansandal/conda-bash-completion#18]
Hi! 
Would it be possible to support `osx-arm64` as a platform, please?
Thanks!

**Comment by jucor** [comment]
Hi @tartansandal ! I've triggered the automatic migration for OSX-arm64, which then triggered conda-forge/conda-bash-completion-feedstock#5 . Once you've merged that latter, I'm not sure if it then automatically reuploads the package to conda-forge. I suspect it does, but I'm new to this. Any idea?
I've done the same triggers for your other package `mamba-bash-completion`, so one should follow the other :)

**Comment by tartansandal** [comment]
Thanks @jucor! I've triggered the merge. I believe that should trigger the upload to conda-forge, but its been a while. Let me know if it does not pop up in the next 24hrs. :smile:

**Comment by jucor** [comment]
Brilliant, thanks, will set a reminder to check in 24 hours and ping you if it doesn't :)
Once this one is done, that should trigger the same bot for `mamba-bash-completion` which was waiting on the update from `conda-bash-completion` since the latter had been detected as a parent of the former.

**Comment by jucor** [comment]
AAAnd it's live on condaforge! 🎉 
![image](https://user-images.githubusercontent.com/660037/223253363-c26ad955-8050-47cd-b3e5-3809c8b7896e.png)

Installed and tested, works like a charm. Expect a similar atuomatic PR in conda-forge/mamba-forge-pinning-feedstock : it is now in `Awaiting PR` status in https://conda-forge.org/status/#armosxaddition :)
