### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ftram** [tartansandal/conda-bash-completion#7]
It is not working for me.
I have installed the package using the command
`conda install -c conda-forge conda-bash-completion`
It has installed:
> bash-completion    conda-forge/osx-64::bash-completion-2.10-1
>   conda-bash-comple~ conda-forge/osx-64::conda-bash-completion-1.5-1
>   python_abi         conda-forge/osx-64::python_abi-3.7-1_cp37m

And updated:
> ca-certificates     pkgs/main::ca-certificates-2020.1.1-0 --> conda-forge::ca-certificates-2020.4.5.1-hecc5488_0
>   certifi              pkgs/main::certifi-2019.11.28-py37_1 --> conda-forge::certifi-2020.4.5.1-py37hc8dfbb8_0
>   conda                       pkgs/main::conda-4.8.3-py37_0 --> conda-forge::conda-4.8.3-py37hc8dfbb8_1
>   openssl              pkgs/main::openssl-1.1.1f-h1de35cc_0 --> conda-forge::openssl-1.1.1g-h0b31af3_0

I have conda version 4.8.3 and I am using macos.
I saw that is a similar issue, but I am not using the zhs shell. Both the login shell and interactive shell is bash.

**Comment by tartansandal** [comment]
Hi @ftram,

Sorry to here this is not working for you. 
Could I just check what version of bash you are using (`bash --version`)?

**Comment by ftram** [comment]
Thanks for quick reply!
The bash version is:
GNU bash, version 5.0.16(1)-release (x86_64-apple-darwin19.3.0)

This is installed (and updated) via homebrew.

**Comment by tartansandal** [comment]
No problem :smile: 
Bash version is good.
Next. Completion setup is triggered by the environment activation hooks.
Is is your `.bashc` setup to run the `conda init` routines and is the default environment active?

**Comment by tartansandal** [comment]
Thanks for that @ftram :smile: 

I don't have access to a Mac at the moment and am largely relying on 3 year old memories, so apologies if I have to ask a lot of simple questions. Your help with this is greatly appreciated.

Miniconda is fine. I know of at least one other person who has that working with `conda-bash-completion`.

Dependencies should have been automatically resolved by conda. There is only one: `bash-completion`.

Using `.bash_profile` is a little unusual. This only gets sourced once during login. I'm wondering if that is being sourced by the old system level bash rather than your newer homebrew bash. (The old system level bash won't work with completion). Some things I'd like to check so we are 100% sure understand what is going on before we make any changes:

```
echo $SHELL
echo $BASH_VERSION
dscl . -read ~/ UserShell
```

I know that you've set you login and default shell to bash, but there is a chance that your login shell is set to the old bash rather than your homebrew version.

**Comment by tartansandal** [comment]
Hi @ftram. Have you made any progress with this? :smile:

**Comment by ftram** [comment]
Sorry, I forgot 😅 I do it now

Il Dom 26 Apr 2020, 04:24 Kahlil (Kal) Hodgson <notifications@github.com>
ha scritto:

**Comment by ftram** [comment]
Sorry, I forgot 😅

So, here the results of the 3 commands:
```
$ echo $SHELL
/bin/bash
$ echo $BASH_VERSION
3.2.57(1)-release
$ dscl . -read ~/ UserShell
UserShell: /bin/bash
```
I add another info:
```
$ /bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```
So it seems your suspect is right

**Comment by ftram** [comment]
Now I have changed the default login shell to` /usr/local/bin/bash` that is the one installed via homebrew (this is done by adding, with sudo, `/usr/local/bin/bash` in `/etc/shells` and executing `sudo chsh -s /usr/local/bin/bash` and restarting the terminal).

Now the 3 commands you suggested give:
```
$ echo $SHELL
/usr/local/bin/bash
$ echo $BASH_VERSION
5.0.17(1)-release
$ dscl . -read ~/ UserShell
UserShell: /usr/local/bin/bash
```
And:
```
$ /bin/bash --version
GNU bash, version 5.0.17(1)-release (x86_64-apple-darwin19.4.0)
```
After this, if I try the bash completion with conda it does not work. But after removing e re-installing `conda-bash-completion` it works perfectly!

Thanks for indicating where the problem could be was! 😄

**Comment by sudonto** [comment]
hi @tartansandal , I have similar problem and I could not figure it out. These are output of commands:
`echo $SHELL` -> /bin/bash
`echo $BASH_VERSION` -> 3.2.57(1)-release
`dscl . -read ~/ UserShell` -> UserShell: /bin/bash

So, what should I do?

**Comment by sudonto** [comment]
And, I put these lines in either `.bashrc` or `bash_profile` with no luck:
`CONDA_ROOT=~/anaconda3   # <- set to your Anaconda/Miniconda installation directory
if [[ -r $CONDA_ROOT/etc/profile.d/bash_completion.sh ]]; then
    source $CONDA_ROOT/etc/profile.d/bash_completion.sh
fi`

**Comment by tartansandal** [comment]
Hi @sudonto.

The `bash-completion` library that `conda-bash-completion` uses depends on a bash version > 4.1. 
The default version of bash on MacOS is very old and only has limited completion facilities. To use `conda-bash-completion` you will need to 

1. install a more modern version of bash via, say, brew
2. set that new bash to be your login shell
3. reboot

Hope this helps :-)
